platform:ios, '9.0'

use_frameworks!

target 'XJHViewState_Example' do
  pod 'XJHViewState', :path => '../'
  
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'MLeaksFinder', '~> 1.0.0'

  target 'XJHViewState_Tests' do
    inherit! :search_paths

    
  end
end
